/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "adserver_constants.h"



const adserverConstants g_adserver_constants;

adserverConstants::adserverConstants() {
}



